### ISSUE TITLE
SimpleServer example doesn't build

### ISSUE THREAD

**Issue by relrod** [kazu-yamamoto/dns#110]
It seems like it hasn't built for quite a while now. Can this be brought up to date? I would find it useful.

**Comment by kazu-yamamoto** [comment]
Thank you for pointing out.
I will try fix it but I'm now busy due to the beginning of Japanese fiscal year.
Please wait for a while.

**Comment by kazu-yamamoto** [comment]
dcf7e308711ba3c40af827aa5627e147bb3201b5 should fix this.

**Comment by kazu-yamamoto** [comment]
I would close this.

**Comment by relrod** [comment]
Thanks, @kazu-yamamoto!
