### ISSUE TITLE
makeResolvSeed throws an error when /etc/resolv.conf contains a non-numeric nameserver

### ISSUE THREAD

**Issue by Kritzefitz** [kazu-yamamoto/dns#115]
Today I encountered this error message in one of my applications that has `dns` as a transitive dependency:

```
werewolf-xmpp: Network.Socket.getAddrInfo (called with preferred socket type/protocol: AddrInfo {addrFlags = [AI_ADDRCONFIG,AI_NUMERICHOST,AI_PASSIVE], addrFamily = AF_UNSPEC, addrSocketType = Datagram, addrProtocol = 0, addrAddress = <assumed to be undefined>, addrCanonName = <assumed to be undefined>}, host name: Just "localhost", service name: Just "domain"): does not exist (Name or service not known)
```

As it turns out, this seems to happen, because my `/etc/resolv.conf` contains an entry like this:

```
nameserver localhost
```

As it turns out calls to `makeResolvSeed defaultResolvConf` throw the exception mentioned above when `/etc/resolv.conf` contains a nameserver with a non-numeric name (such as the `localhost` above). This is because `getAddrInfo` is given the `AI_NUMERICHOST` option, when `localhost` is clearly not a numeric host.

Now, I know it might seem reasonable to assume that `/etc/resolv.conf` may only contain numeric addresses, because you can't do dns lookups before having read that file, but the assumption doesn't actually hold up, because hostnames that can be resolved via `/etc/hosts` (or some other strange way people might have configured in their libnss) work just fine in `/etc/resolv.conf`. This `dns` library is really the only piece of software that seems to have a problem with this setup.

Of course I can just work around this by replacing the `localhost` with `127.0.0.1` or `::1`, but IMO this should really be something that should just work out of the box.

**Comment by kazu-yamamoto** [comment]
Do you suggest to remove `AI_NUMERICHOST` in `makeAddrInfo`?
If so, I will.

**Comment by kazu-yamamoto** [comment]
I would like to add an option to the configuration to allow host names in `/etc/resolv.conf`. Its default value is `False`. Make sense?

**Comment by Kritzefitz** [comment]
I think making this a configuration option that defaults to `False` is a bad idea. `/etc/resolv.conf` already is *the* place to configure the resolvers for your system, configuring somewhere else how that file should be parsed is just redundant. It's even worse if that configuration option is controlled by the application using this dns library (rather than the user), because then the application has to deviate from the standard to just do the right thing.

Do you see any particular problem with allowing host names in `/etc/resolv.conf`?

**Comment by vdukhovni** [comment]
I've seen no evidence that non-numeric hostnames are valid in /etc/resolv.conf, and so it rather seems that this change is not needed. The name "localhost" is not defined in that context. Perhaps some libraries ignore unsupported names and then default to 127.0.0.1?  One might argue that Network.DNS should not error out, and simply ignore invalid names, but I don't think that resolving non-numeric names is correct in this context.

* Linux resolv.conf(5) manpage:
```
nameserver Name server IP address
    Internet address of a name server that the resolver should
    query, either an IPv4 address (in dot notation), or an IPv6
    address in colon (and possibly dot) notation as per RFC 2373.
    Up to MAXNS (currently 3, see <resolv.h>) name servers may be
    listed, one per keyword.  If there are multiple servers, the
    resolver library queries them in the order listed. If no
    nameserver entries are present, the default is to use the name
    server on the local machine.  (The algorithm used is to try a
    name server, and if the query times out, try the next, until
    out of name servers, then repeat trying all the name servers
    until a maximum number of retries are made.)
```

FreeBSD resolv.conf(5):
```
     nameserver  Internet address (in dot notation) of a name server that the
                 resolver should query.  Up to MAXNS (currently 3) name
                 servers may be listed, one per keyword.  If there are
                 multiple servers, the resolver library queries them in the
                 order listed.  If no nameserver entries are present, the
                 default is to use the name server on the local machine.  (The
                 algorithm used is to try a name server, and if the query
                 times out, try the next, until out of name servers, then
                 repeat trying all the name servers until a maximum number of
                 retries are made).
```

NetBSD resolv.conf(5) manpage
```
     nameserver  IPv4 address (in dot notation) or IPv6 address (in
                 hex-and-colon notation) of a name server that the resolver
                 should query.  Scoped IPv6 address notation is accepted as
                 well (see inet6(4) for details).  Up to MAXNS (currently 3)
                 name servers may be listed, one per keyword.  If there are
                 multiple servers, the resolver library queries them in the
                 order listed.  If no nameserver entries are present, the
                 default is to use the name server on the local machine.  (The
                 algorithm used is to try a name server, and if the query
                 times out, try the next, until out of name servers, then
                 repeat trying all the name servers until a maximum number of
                 retries are made).
```

**Comment by vdukhovni** [comment]
On my system, when I use `nameserver localhost` (listed in `/etc/hosts`) or `nameserver bogushost` (fictional name not listed in `/etc/hosts`), ... the effect is the same. The nameserver address used is the wildcard `0.0.0.0`, which happens to "work", in that a local resolver on "127.0.0.1" sees the request and answers, but this opens the stub resolver to more reply spoofing, because it is no longer bound to just the expected server address. So if 'nameserver localhost` "works", it is entirely an accident, which Network.DNS does not need to emulate, though when nothing else is found, we could default to 127.0.0.1 rather than 0.0.0.0.

System call trace with `nameserver localhost` or `nameserver bogushost`:
```
socket(PF_INET,SOCK_DGRAM|SOCK_CLOEXEC,0)        = 3 (0x3)
connect(3,{ AF_INET 0.0.0.0:53 },16)             = 0 (0x0)
sendto(3,"...",46,0,NULL,0) = 46 (0x2e)
poll({ 3/POLLRDNORM },1,5000)                    = 1 (0x1)
recvfrom(3,"..",65536,0,{ AF_INET 127.0.0.1:53 },0x7fffffff9258) = 62 (0x3e)
```

System call trace with `nameserver 127.0.0.1`:
```
socket(PF_INET,SOCK_DGRAM|SOCK_CLOEXEC,0)        = 3 (0x3)
connect(3,{ AF_INET 127.0.0.1:53 },16)           = 0 (0x0)
sendto(3,"...",46,0,NULL,0) = 46 (0x2e)
poll({ 3/POLLRDNORM },1,5000)                    = 1 (0x1)
recvfrom(3,"...",65536,0,{ AF_INET 127.0.0.1:53 },0x7fffffff9258) = 62 (0x3e)
```

**Comment by Kritzefitz** [comment]
Apparently you're right. My system call trace is slightly different, in that it opens a connection to `127.0.0.1` when I use bogushost (no matter if it's defined in `/etc/hosts` or not). Which dns lookup tool did you use to make these traces? I used `strace getent hosts <host>`. Maybe the default (`127.0.0.1` vs `0.0.0.0`) differs depending on the exact tool/version.

I'm sorry for making a fuss about this. Apparently I just had a wrong configuration that I thought was correct due to incorrect assumptions.

**Comment by vdukhovni** [comment]
> @Kritzefitz Which dns lookup tool did you use to make these traces?

I avoided `getent hosts` because that is rather specialised code.  Instead I traced `nc ssh-server-not-in-etc-hosts.example 22`, which just does a routine getaddrinfo().  To be sure, you could compile and test:
https://raw.githubusercontent.com/vdukhovni/postfix/master/postfix/auxiliary/name-addr-test/getaddrinfo.c

**Comment by Kritzefitz** [comment]
Both `nc` and `getaddrinfo.c` also seem to use `127.0.0.1` by default on my system. The exact default probably depends on libnss or libs or some other library involved in name resolution, but I guess that's not really important for this issue.

**Comment by kazu-yamamoto** [comment]
It seems that we reached consensus. I close this and #118.
