### ISSUE TITLE
travis CI failure

### ISSUE THREAD

**Issue by kazu-yamamoto** [kazu-yamamoto/dns#131]
doctest fails for GHC 8.0 and GHC 8.2 due to library import path.

What I found:

Old good:

> cabal-install version 2.4.0.0
> compiled using version 2.4.0.1 of the Cabal library 

New bad:

> cabal-install version 2.4.1.0
> compiled using version 2.4.1.0 of the Cabal library

**Comment by kazu-yamamoto** [comment]
Travis including doctest is now OK.
doctest on Appveyor does not finish.

Cc: @vdukhovni

**Comment by vdukhovni** [comment]
I pushed a commit to  make doctest verbose, and it appears to not even start any of the tests.  This feels like a portability issue with GHC and doctest on Windows, rather than anything in Network.DNS.  Is this new doctest interface working in other projects?

**Comment by vdukhovni** [comment]
Could it be related to this issue: https://github.com/sol/doctest/issues/216

**Comment by vdukhovni** [comment]
That does not seem to be it, or the fix is incomplete...  No idea why it hangs on Windows.

**Comment by kazu-yamamoto** [comment]
> Is this new doctest interface working in other projects?

Yes.

- https://github.com/kazu-yamamoto/unix-time
- https://github.com/kazu-yamamoto/logger

And I'm now tackling to `dns` and `network`.

- https://github.com/haskell/network/pull/362

**Comment by kazu-yamamoto** [comment]
Using GHC 8.4.4 solved this issue. Don't know why.

**Comment by kazu-yamamoto** [comment]
GHC 8.6.2 also works. I'm sure that this is due to GHCi 8.6.3's bug:  https://ghc.haskell.org/trac/ghc/ticket/16057
