### ISSUE TITLE
Some day fully hide internal modules used only in tests

### ISSUE THREAD

**Issue by vdukhovni** [kazu-yamamoto/dns#133]
As of Cabal 2.0, it is now possible to have internal libraries exposed for testing, but not in the public library:

https://cabal.readthedocs.io/en/latest/developing-packages.html#sublibs

This could be used in principle in Network.DNS, but would take some work, as the current internal modules also import some of the public modules.

We would therefore I think have to move some code into internal modules, and re-export it from the public modules, so that the dependencies in the internal sub-library are self-contained.

Not sure whether it is worth it, or whether we're yet ready to remove support for all GHC versions that predate Cabal 2.0.  So perhaps just something to keep in mind for the future...

**Comment by vdukhovni** [comment]
This is perhaps addressed in #140

**Comment by kazu-yamamoto** [comment]
Resolved in #140.
