### ISSUE TITLE
Releasing 4.0.1

### ISSUE THREAD

**Issue by kazu-yamamoto** [kazu-yamamoto/dns#148]
- [ ] Changelog

@vdukhovni Would you update `Changelog.md`?

**Comment by vdukhovni** [comment]
> * [ ]  Changelog
> 
> @vdukhovni Would you update `Changelog.md`?

Thanks, I'll put something together over the next week or so...

**Comment by vdukhovni** [comment]
Done. Please feel free to edit or request changes as appropriate.

**Comment by kazu-yamamoto** [comment]
`cabal sdist` genarated a lot of errors. 31f9f4da0dc211b575b1fe58cc68ea6705d445d7 tries to fix these.

I'm waiting for the result of CI.

**Comment by kazu-yamamoto** [comment]
CI passed. I've released a new version.
