### ISSUE TITLE
dropping appveyor

### ISSUE THREAD

**Issue by kazu-yamamoto** [kazu-yamamoto/dns#160]
@vdukhovni Should we drop CI of appveyor?

**Comment by vdukhovni** [comment]
Probably yes. How are you finding the Github CI?  I don't know very much about Github CI just yet, so it would be good if someone more fluent in it took a closer look.
Are you satisfied with the results?

**Comment by kazu-yamamoto** [comment]
I'm now learning github actions. So, I cannot say anything at this moment.

**Comment by kazu-yamamoto** [comment]
I dropped AppVeyor anyway and added a badge in README.md.

**Comment by vdukhovni** [comment]
We could try to test more GHC versions on Windows?
And perhaps enable doctests in 9.0 when it comes out (soon), perhaps the new WIndows I/O manager solves the previous issues?

**Comment by kazu-yamamoto** [comment]
To my experience, test on Windows takes much time. I guess one version of Windows is good enough but this is not a strong opinion.

Let's revisit doctest when GHC 9.0 is available.

**Comment by vdukhovni** [comment]
Sure. I might note that github actions seems to do a pretty good job of caching previous build artefacts (dependencies, toolchain, ...) so that incremental builds are faster IIRC, but it's been a while, so I'm not sure this is the case.

Once 9.0 comes out, we can add it to the matrix, and see how long the builds take, if they're fast, we could test 8.6, 8.8, 8.10 and 9.0.

**Comment by kazu-yamamoto** [comment]
`network` switched to github actions based on your CI script. :-)

**Comment by vdukhovni** [comment]
> `network` switched to github actions based on your CI script. :-)

For the record, I just tweaked the one from `bytestring`, which someone else wrote.
Did you see the recent discussion on haskell-cafe with suggestions for github-ci?

**Comment by kazu-yamamoto** [comment]
Did not. But I have read it now.
