### ISSUE TITLE
Dropping GHC 7.x #ifdefs?

### ISSUE THREAD

**Issue by vdukhovni** [kazu-yamamoto/dns#162]
CI does no longer tests GHC 7.x. When should we drop the #ifdefs that conditionally switch between sums and pattern synonyms?

**Comment by kazu-yamamoto** [comment]
I think we can do it right now.

**Comment by vdukhovni** [comment]
> I think we can do it right now.

OK, I'm adding commits the the "RP" pull request that drop GHC 7.x support by deleting the "non-pattern-synonym" conditionally compiled code.
