### ISSUE TITLE
Releasing a new version

### ISSUE THREAD

**Issue by kazu-yamamoto** [kazu-yamamoto/dns#168]
I would like to release a new version. I modified the version to 4.0.2 currently. However, since this release does not support GHC 7.x, I wonder whether or not we should release it as 4.1.0.

**Comment by vdukhovni** [comment]
> I would like to release a new version. I modified the version to 4.0.2 currently. However, since this release does not support GHC 7.x, I wonder whether or not we should release it as 4.1.0.

No objections to the major version bump.

**Comment by kazu-yamamoto** [comment]
OK. I will release 4.1.0 soon.

**Comment by kazu-yamamoto** [comment]
Done. Thanks!
