### ISSUE TITLE
cryptonite dependency

### ISSUE THREAD

**Issue by bjin** [kazu-yamamoto/dns#171]
Just a FYI. This package still depends on `cryptonite`, maybe you want to move to the new `crypton` package?

Also it seems that `cryptonite` is used to generate random numbers. If cryptographically secure RNG is not required for DNS resolvers, maybe the whole dependency could be dropped?

**Comment by kazu-yamamoto** [comment]
I will switch `cryptonite` to `crypton` and release v4.2.0.

I'm not active to maintain this package because we are developing `dnsext`.
So, I don't modify `dns` more.
Note that `dnsext-dnssec` requires `crypton` to verify DNSSEC.

**Comment by kazu-yamamoto** [comment]
v4.2.0 has been released.
