### ISSUE TITLE
From Example: recvFrom: failed (Connection reset by peer (WSAECONNRESET))

### ISSUE THREAD

**Issue by 3noch** [kazu-yamamoto/dns#24]
Again, this might simply be outside scope, but the example server eventually crashes with this error (on Windows).

`recvFrom: failed (Connection reset by peer (WSAECONNRESET))`

Any ideas?

**Comment by vdukhovni** [comment]
Perhaps the server example should just be removed, there's more to implementing a DNS Server that is present in this naïve example.  Closing the issue for now.
