### ISSUE TITLE
The identifier of DNSHeader can only hold 16 bits integers.

### ISSUE THREAD

**Issue by redneb** [kazu-yamamoto/dns#27]
I was debugging a misbehaving program of mine today and I found out that the bug was caused by writing an integer greater than 65535 to the `identifier` of a `DNSHeader`. Currently that field has type `Int` but a DNS message has room for only 16 bits to written there. The problem is that `encode` (from `Network.DNS.Encode`) silently performs a lossy conversion discarding the excess bits. This can lead to various unexpected bugs.

Maybe `encode` could be modified so that it raises an exception if a value larger than 65535 is provided. Or the type of that field could be changed to `Word16`. I would prefer the latter, but unfortunately that would be a breaking change.

**Comment by kazu-yamamoto** [comment]
I also like `Word16` and think its effect is small because it is a low API. Let's bump up the version to 1.5 to express this breaking change. Would you give me a pull request?

**Comment by redneb** [comment]
> Would you give me a pull request?

Will do.
