### ISSUE TITLE
not threadsafe

### ISSUE THREAD

**Issue by mwotton** [kazu-yamamoto/dns#32]
I found that with code like this:

```
gatherDNS :: IO (Domain  -> IO [(TYPE, [ByteString])])
gatherDNS = do
  resolvSeed <- makeResolvSeed $ defaultResolvConf { resolvInfo = RCFilePath "/etc/resolv.conf" }
  return $ \dom -> do
    withResolver resolvSeed $ \r -> do
      (`mapConcurrently` dnsFetchers) $ \fetch ->
        (t,res) <- fetch r dom
        return (t,sort res)

dnsFetchers :: [Resolver -> Domain -> IO (TYPE, [ByteString])]
dnsFetchers = [ mxFetcher
              , spfFetcher
              ]

mxFetcher :: Resolver -> Domain -> IO (TYPE,[ByteString])
mxFetcher resolv dom =  processor <$> lookupMX resolv dom
  where processor = (MX,) . either (const []) (map fst)

spfFetcher :: Resolver -> Domain -> IO (TYPE,[ByteString])
spfFetcher resolv dom  = processor <$> lookupTXT resolv dom
  where processor = (TXT,) . either (const []) id

```

it would not work reliably. swapping the order of the withResolver and mapConcurrently lines corrected this.

**Comment by kazu-yamamoto** [comment]
Parallel lookups are not supported in one resolver. If you really want that, we need to investigate what is critical section.

**Comment by mwotton** [comment]
I don't particularly need it, but the semantics could be clearer - there doesn't seem to be anything in the documentation telling you that sharing resolvers is not ok.

**Comment by mwotton** [comment]
(basically, I saw "thread-safe" and immediately thought "ok, it's an immutable value" and didn't think about it any more :) )

**Comment by kazu-yamamoto** [comment]
For parallel lookup, `withResolvers` should be used. See the concurrent-dns-cache package as example.

Yes, documentation is poor. I will update what thread-safe means.

**Comment by kazu-yamamoto** [comment]
Does the patch above make sense?

**Comment by mwotton** [comment]
yep, that's great :+1:

**Comment by kazu-yamamoto** [comment]
Thanks.

**Comment by kazu-yamamoto** [comment]
I have released a new version.
