### ISSUE TITLE
Support leftovers in decode

### ISSUE THREAD

**Issue by paf31** [kazu-yamamoto/dns#33]
If multiple messages are sent at once (e.g. when using TCP as the transport), it is currently impossible to decode all messages from a single lazy `ByteString`. Adding a variant of `decode` which returned leftovers would solve this problem. Another option would be to provide a `decodeMany` function.

I'm happy to send a PR if this sounds generally useful.

**Comment by kazu-yamamoto** [comment]
Sounds lovely. Please show me your code. I would like to take the option which maintains API compatibility.

I think I will be able to take time in the next week. (I'm busy in this week.)

**Comment by paf31** [comment]
I'm preparing a PR at the moment. I'll probably have something tomorrow. It will be a backwards-compatible change.

**Comment by kazu-yamamoto** [comment]
A new version has been released.
