### ISSUE TITLE
add Identifier matching

### ISSUE THREAD

**Issue by riaqn** [kazu-yamamoto/dns#44]
By far there can be only one request session going on in a resolver; this shouldn't be the case: there is the identifier field that's meant to be used to match requests and responses, enabling us to handle several requests simultaneously. It may also help with the efficiency thing: we don't have to open an UDP socket for every concurrent requests.

Also, I would really appreciate it if DNS over TCP can be implemented(then again, we need the identifier matching support, otherwise it can be really slow).

**Comment by kazu-yamamoto** [comment]
I have no time to take care of this. But if you volunteer, I would love to merge your code.

**Comment by riaqn** [comment]
I'm closing this issue as I don't need it anymore since I have my own DNS library now : https://github.com/riaqn/resolve/ . But anyone please feel free to reopen it if needed.
