### ISSUE TITLE
Does not build on Windows

### ISSUE THREAD

**Issue by Alxandr** [kazu-yamamoto/dns#48]
Hi. This package does not build on windows. I was told on IRC that is was likely to be the lines here: https://github.com/kazu-yamamoto/dns/blob/master/Network/DNS/Resolver.hs#L442-L448

```
dns-2.0.10: configure
dns-2.0.10: build
Progress: 1/2
--  While building package dns-2.0.10 using:
      C:\sr\setup-exe-cache\x86_64-windows\Cabal-simple_Z6RU0evB_1.24.0.0_ghc-8.0.1.exe --builddir=.stack-work\dist\b7fec021 build --ghc-options " -ddump-hi -ddump-to-file"
    Process exited with code: ExitFailure 1
    Logs have been written to: C:\Users\alxan\Documents\GitHub\cheat\.stack-work\logs\dns-2.0.10.log

    Configuring dns-2.0.10...
    Building dns-2.0.10...
    Preprocessing library dns-2.0.10...
    [1 of 9] Compiling Network.DNS.Internal ( Network\DNS\Internal.hs, .stack-work\dist\b7fec021\build\Network\DNS\Internal.o )
    [2 of 9] Compiling Network.DNS.Types ( Network\DNS\Types.hs, .stack-work\dist\b7fec021\build\Network\DNS\Types.o )
    [3 of 9] Compiling Network.DNS.StateBinary ( Network\DNS\StateBinary.hs, .stack-work\dist\b7fec021\build\Network\DNS\StateBinary.o )
    [4 of 9] Compiling Network.DNS.Decode ( Network\DNS\Decode.hs, .stack-work\dist\b7fec021\build\Network\DNS\Decode.o )
    [5 of 9] Compiling Network.DNS.Encode ( Network\DNS\Encode.hs, .stack-work\dist\b7fec021\build\Network\DNS\Encode.o )
    [6 of 9] Compiling Network.DNS.Utils ( Network\DNS\Utils.hs, .stack-work\dist\b7fec021\build\Network\DNS\Utils.o )
    [7 of 9] Compiling Network.DNS.Resolver ( Network\DNS\Resolver.hs, .stack-work\dist\b7fec021\build\Network\DNS\Resolver.o )

    C:\Users\alxan\AppData\Local\Temp\stack11708\dns-2.0.10\Network\DNS\Resolver.hs:445:21: error:
        parse error on input `='
        Perhaps you need a 'let' in a 'do' block?
        e.g. 'let x = 5' instead of 'x = 5'
```

**Comment by kazu-yamamoto** [comment]
@Alxandr I think `sendAll` should be a top level function. Would you try to remove the leading four spaces from the area surrounded by `#`? If it works, please send me a pull request.

**Comment by Alxandr** [comment]
I tried that, and it builds. But there are other problems. All the tests gets timeout exceptions (which I don't know how to debug). I'm fairly new to haskell. Another problem is that windows doesn't have `/etc/resolv` so I changed the default windows one to be "8.8.8.8" (with some comments on the fact that it should probably get the system dns by way of either ipconfig or netstat).

**Comment by dcoutts** [comment]
@kazu-yamamoto we have written some code for getting the default system DNS server on Windows. Is that something you'd be interested in integrating into the DNS package so that things can work out of the box on Windows in the same way it works on Unix based systems?

https://github.com/input-output-hk/cardano-sl/tree/f19ce1845760dc4c5d984811a8908474d97914cb/infra/Pos/Network/Windows

This would need to be slightly cleaned up to integrate into the lib (e.g. removing C printfs for error reporting etc) but it should be a good start.

**Comment by kazu-yamamoto** [comment]
@dcoutts Absolutely interested. Please give me a PR.
Note that I'm very busy in August due to NetPL 2017 (SIGCOMM) as you may know.
I will tackle issues on DNS in September.
Sorry for your inconvenience.

**Comment by kazu-yamamoto** [comment]
I set up AppVeyor.
Now I can check whether or not the dns library can be complied.
But the test on AppVeyor fails because lack of /etc/resolv.conf.

@dcoutts Your PR is highly welcome.

**Comment by kazu-yamamoto** [comment]
I'm working on this by myself.

**Comment by kazu-yamamoto** [comment]
@dcoutts I integrated your code to detect a DNS server on Windows.
Please open an issue if any credits are necessary.
