### ISSUE TITLE
Add testing on AppVeyor

### ISSUE THREAD

**Issue by Alxandr** [kazu-yamamoto/dns#49]
Add appveyor testing to assert it works on Windows.

**Comment by erikd** [comment]
@Alxandr If @kazu-yamamoto is not familiar with Appveyor, maybe you could provide a PR.

**Comment by kazu-yamamoto** [comment]
I don't use Windows and Appveyor.
PR is very welcome.

**Comment by Alxandr** [comment]
Setting up AppVeyor to do testing on Windows is fairly easy. Just copy the following file to your repo: https://github.com/commercialhaskell/stack/blob/master/appveyor.yml, then go to AppVeyor and sign up (just like you did with Travis). Considering you're using stack that should be all that's needed.

**Comment by kazu-yamamoto** [comment]
I setup AppVeyor.
