### ISSUE TITLE
Investigate and hopefully fix OptRecord

### ISSUE THREAD

**Issue by erikd** [kazu-yamamoto/dns#55]
In the round trip tests, the [OptRecord](https://github.com/kazu-yamamoto/dns/blob/master/test/RoundTripSpec.hs#L84-L85) variant of the `ResoruceRecord` generator is currently disabled (its frequency set to zero) because it does not correctly round-tip.

I *think* the decoder for this field is at least partially  correct, but doubt the encoder is correct.

Best way to debug this would be to get a Pcap dump that includes an `OptRecord` field to make sure the decoder can decode real world data, then make sure the encoder is working and finally re-enable the `OptRecord` generator.

@kazu-yamamoto I am willing to take on this task.

**Comment by kazu-yamamoto** [comment]
@erikd `ResourceRecord` is not a sum type anymore.
Now we can use utilities functions starting with `or`.
Please add test cases again.
I will investigate it if possible.

**Comment by kazu-yamamoto** [comment]
I'm tackling this issue by myself and considering proper APIs.

**Comment by erikd** [comment]
Sorry, I've been super busy at the moment. If you get something together I'd be happy to review it, but i don't currently have the cycles to investigate this myself.

**Comment by kazu-yamamoto** [comment]
This has been fixed in the `ghc8` branch with a new EDNS0 framework.

**Comment by erikd** [comment]
Code looks good to me! Thanks @kazu-yamamoto !
