### ISSUE TITLE
Define a proper error type

### ISSUE THREAD

**Issue by erikd** [kazu-yamamoto/dns#56]
Currently, a function like `decode` is defined as:
```
decode :: ByteString -> Either String DNSMessage
```
which reports all errors simply as `String`.

The problem with using `String` for errors is that it is not possible to robustly pattern match on them. For instance, if I write code that matches one of the current error messages, but a later version of this packages changes that error message, my pattern match will silently fail.

Instead I propose a data type something like:
```
data DNSError
    = DNSError1 ....
    | DNSError2 ....
```
and so on. This makes the error type part of the API, so that if a `DNSError` constructor is removed or changed in any way, my code would now fail to compile instead of silently failing. 

This proposal would also add a function to render that `DNSError` to `String` (or maybe even `Text`):
```
renderDNSError :: DNSError -> String
```
so that the original `decode` function would now have type:
```
decode :: ByteString -> Either DNSError DNSMessage
```

@kazu-yamamoto What do you think of this idea? If you like it, I'll do it over the weekend.

**Comment by kazu-yamamoto** [comment]
I support your idea!

**Comment by kazu-yamamoto** [comment]
I would close this in favor of #107.
