### ISSUE TITLE
ResourceRecord field names

### ISSUE THREAD

**Issue by kazu-yamamoto** [kazu-yamamoto/dns#63]
@erikd I'm trying to release a new version to save Windows and fix some bugs that you fixed.
`concurrent-dns-cache` cannot be build with `master` of `dns`. 
This is because you removed fields names in 8f51a20241dee0c9e86d1e020139f23dd565bc5d.
Would you tell me the reason why you remove them?

And if you introduced any breaking changes from version 2.0.10, please let me know.

**Comment by erikd** [comment]
I removed them because they were partial functions. I really try to avoid partial functions in my code, especially at what is effectively the library API.

In more detail, the original data structured looked like:
```
data ResourceRecord = ResourceRecord {
                            rrname :: Domain
                          , rrtype :: TYPE
                          , rrttl  :: Int
                          , rdata  :: RData
                          }
                    | OptRecord {
                            orudpsize   :: Int
                          , ordnssecok  :: Bool
                          , orversion   :: Int
                          , rdata       :: RData
                          }
                    deriving (Eq,Show)
```
Using the `rrname` accessor on a value created with the `OptRecord`constructor results in a run time pattern match failure. The correct way to use the `rnname` accessor is to first pattern match to ensure that the value uses the `ResourceRecord` constructor, but, there is no way for the compiler to enforce this.

The type of the `rnname` accessor should really be:
```
rnname :: ResourceRecord -> Maybe Domain
```
to show that it can fail.

**Comment by kazu-yamamoto** [comment]
I would like to invite @greydot to this issue.

**Comment by kazu-yamamoto** [comment]
@erikd I will do two things:

- I will release 2.0.11 ASAP to save Windows. In this version, I would like to include some bug fixes.
- I will brush up the data types and functions on `master`.

I would like to use this issue to discuss the latter and open a new issue for the former.

**Comment by kazu-yamamoto** [comment]
Assuming *major* changes:

Since `OptRecord` is really special, I would like to change `ResourceRecord`:

```
data ResourceRecord = ResourceRecord {
                            rrname  :: Domain
                          , rrclass :: Word16
                          , rrtype  :: TYPE -- Word32
                          , rrttl   :: TTL
                          , rdata   :: RData
                          } deriving (Eq,Show)
```

Now we have CLASS, so we can convert this to `OptRecord`:

```
data OptRecord = OptRecord {
                      orudpsize   :: Word16
                    , ordnssecok  :: Bool
                    , orversion   :: Word8
                    , orrdata     :: RData
                    }
                    deriving (Eq,Show)
```

Field labels are now total.

@greydot What do you think?

**Comment by erikd** [comment]
I will also note that there is still an issue with the current handling of `OptRecord` (issue #55 ).

The RFCs were not sufficiently clear for me to fix that without reference to a couple of packet dumps captured in the wild and I have not yet been able to capture any such packet dumps.

**Comment by kazu-yamamoto** [comment]
@erikd Thanks. Yes, it is hard to read RFCs relating to DNS. X-(

**Comment by kazu-yamamoto** [comment]
I have implemented this idea: https://github.com/kazu-yamamoto/dns/tree/opt-record

No conversion functions yet.

**Comment by greydot** [comment]
@kazu-yamamoto I agree on splitting ResourceRecord into two distinct types. The original code sort of reflects the fact that Opt records are a hack in the standard, and I didn't know any better at the time.

I also think that instead of RR <-> OR conversion functions a new sum type would be more suitable.

**Comment by kazu-yamamoto** [comment]
> I also think that instead of RR <-> OR conversion functions a new sum type would be more suitable.

Would you show this idea as code?

**Comment by greydot** [comment]
I meant something like this
`data Record = RR ResourceRecord | OR OptRecord`
but after investigating a bit further, it seems this approach would require even more changes to the code, i.e. changing the definition of DNSMessage and splitting Decode.getResourceRecord and Encode.putResourceRecord into two functions each. While this arguably could be better when it comes to correctness, backwards compatibility will be hit pretty hard.

**Comment by kazu-yamamoto** [comment]
Instead of defining the conversion function, I added utilities functions to extract OPT-RR fields from ResourceRecord.

2c9ffe24efdd8e86a83a1f43a65a45130a1cf21c
