### ISSUE TITLE
stable-2.0

### ISSUE THREAD

**Issue by kazu-yamamoto** [kazu-yamamoto/dns#64]
I created https://github.com/kazu-yamamoto/dns/tree/stable-2.0

@erikd Please tell me other commits which you want to include.

**Comment by erikd** [comment]
Is this just another release in the existing 2.0.X series? If so, commit 80bba88546 is the only one that really *needs* to go in.

**Comment by kazu-yamamoto** [comment]
> Is this just another release in the existing 2.0.X series?

Yes.

> If so, commit 80bba88 is the only one that really needs to go in.

Thanks. It is already in this branch.

So, I think all set and ready to go.

**Comment by kazu-yamamoto** [comment]
v2.0.11 has been released.
