### ISSUE TITLE
2.0.11 is broken on Windows due to eaten spaces (by Hackage?)

### ISSUE THREAD

**Issue by adinapoli-iohk** [kazu-yamamoto/dns#65]
Hey @kazu-yamamoto !

Looks like we had more trouble in paradise following [2.0.11 release](https://github.com/kazu-yamamoto/dns/pull/62). I don't know what happened here, but the code looks indeed correct on GitHub, but if we look at the package which landed on Hackage, the spaces of that `sendAll` functions seems to be completely eaten out:

http://hackage.haskell.org/package/dns-2.0.11/docs/src/Network-DNS-Resolver.html

As a temporary workaround, we had to depend on the Github version of this package, but it would be nice to understand what went wrong during upload and fix it (if it's something in my power so that I can open a PR).

Last but not least, given all the different woes we have witnessed on Windows lately, I think it would be outstanding if you could setup this project to [work with Appveyor](https://github.com/kazu-yamamoto/dns/issues/49). In that issue I've linked there are already instructions on how to do that, and I think you are the only one in the position of performing the steps as only the project owner can register the package on Appveyor (IIRC) 😉 

Thank you very much for all your open source contributions, I'm a big fan of your work!

Alfredo

**Comment by kazu-yamamoto** [comment]
This is my fault.
Probably you are looking `master` while I made a mistake on `stable-2.0`.
I have released a new version.

**Comment by kazu-yamamoto** [comment]
I will setup Appveyor. But it will take time since I'm now on summer vacation.

**Comment by adinapoli-iohk** [comment]
> I have released a new version.

No need to apologise, and thank you very much!

> I will setup Appveyor. But it will take time since I'm now on summer vacation.

haha, awesome, thank you! Have a nice one then! 🏄

**Comment by adinapoli-iohk** [comment]
This was fixed weeks ago, so we can close.
