### ISSUE TITLE
Disappearance of `rrname`, `rrtype`, `rrttl` and `rdata` accessors of ResourceRecord

### ISSUE THREAD

**Issue by vdukhovni** [kazu-yamamoto/dns#68]
Some recent commits have removed the "record" form of ResourceRecord, leaving only a multi-slot constructor.  Existing code that used the accessors must now change to define its own accessors.  Only getRdata has been provided.

What motivates these changes?  They seem ill-advised.  In particular they fundamentally break the previous API and all existing applications using Network.DNS would have to change.  I think that these changes should also be reverted...

**Comment by kazu-yamamoto** [comment]
See #63.

**Comment by vdukhovni** [comment]
Well, given the existing API, and the rather meager gains in safety by avoiding partial functions (since most applications will never handle DNSMessage objects and will just deal with answers and perhaps authority and additional records where OPT records don't appear), my contention is that #63 is misguided, and does not adequately justify breaking API.

A related major problem is the disappearance of the custom Show instances for RData, these need to come back.

**Comment by vdukhovni** [comment]
Pull request #70 addresses this and other issues, and passes all tests (a couple of tests needed to be fixed, and others have also opened smaller pull requests for a subset of the test failures).  There is no visible breakage from having separate accessors for the different branches of the ResourceRecord sum type.

**Comment by kazu-yamamoto** [comment]
I have merged #70.
But `ResourceRecord` is not a sum type anymore.
Accessors came back, so minimum backward compatibility recovered.
@vdukhovni I would like to hear your opinion.

**Comment by vdukhovni** [comment]
Thanks, one quick observation... I notice you did not merge the change that changed the 1 ms timeout to 0ms to test a forced timeout.  Unfortunately, on my system with a local resolver, a 1 ms timeout does not reliably fail to perform the lookup, while 0ms does work.  Please consider adopting that change

```
 --   >>> let hostname = Data.ByteString.Char8.pack "www.example.com"
---   >>> let badrc = defaultResolvConf { resolvTimeout = 0, resolvRetry = 1 }
```

**Comment by vdukhovni** [comment]
Otherwise, my initial impression (not a thorough code review) is that the changes look fine.  Thanks.

**Comment by vdukhovni** [comment]
FWIW, my code compiles without warnings and seems to run correctly against the master DNS branch.  Below is how it reports the DS, DNSKEY and SOA records for "mil." (chosen in part for its "interesting" SOA mailbox name).

```
mil. IN DS 34306 8 1 feeae1c81f1f1be80dfc4e7cc46197e706ae80f4 ; NoError AD=1
mil. IN DS 34306 8 2 574e4e56b97b903be130ac4eb1d145a5acd1918cfa4bf425ad3538471a18ee23 ; NoError AD=1
mil. IN DNSKEY 256 3 8 AwEAAeACGCZvDsdZyZd565KzBuD50+UInKg2VYEUD81NUHmePdo/3DB5H48ngZERQjxsFoWDJVnDzVrTAKk9aJLL61/w8X1t+CixuRwgs8wnwtdhvaiXICst3fyjLFChKcHEct8vZWhOtezQx8rhU5bnwqaP315NFHBytbaz1NyUYLFh ; NoError AD=1
mil. IN DNSKEY 256 3 8 AwEAAeWxTUwI1D1bOVV05bV483iqSvv0S3oVPkXoMLKJaNSGbBvyE45YbgYZr/AyddAZsZSErttpdJvFr3EBFFruN3NILTIJ2oEn5r62Qm8Eaq3OJ5Gjgl7Pome/eWOq8U0PZ4FzwcODEi4nnaxMF0wcPLp99J4+d0f3aBRjQa86b7CD ; NoError AD=1
mil. IN DNSKEY 257 3 8 AwEAAah9GUIdwrIXIsSacHJbq9fREwd6ICvnYdd8JHpKY+Wc+f2IZtCy06Ikf8uwgykrTjVu3DTH8YN71RHevo/9bGUVivPa9ux4PIkdKMWdeATGiA+7rw4cRed4Zc9j1Sv+RVK40sL+Hnlf+eSj6iQKHNDMqbu8b6aLkl71ZRPhCy8jo0o2Wz5mHI8gQNWrJM80i5kPOulh2ZZ1K+hCjcXfYY9SMyBZdfr1ygH5zVfXM81OIloNvUlE/1z31cA8/Do1nvLszXpykFZX0Sav69YsKAMO5itllrgmzZA4FTjgdlflt8MRDjhatjYajSUCmwNmQUqWiwkgCyRCNOyCXbxg4T8= ; NoError AD=1
mil. IN SOA CON1.NIPR.mil. DISA.COLUMBUS.NS.MBX.HOSTMASTER-DOD-NIC@MAIL.mil. 2017090102 3600 900 1209600 10800 ; NoError AD=1
```

For `ietf.org` the report shows MX/A/TLSA data and TLS chain data from the SMTP server:
```
ietf.org. IN DS 45586 5 1 d0fdf996d1af2ccdbdc942b02cb02d379629e20b ; NoError AD=1
ietf.org. IN DS 45586 5 2 67fcd7e0b9e0366309f3b6f7476dff931d5226edc5348cd80fd82a081dfcf6ee ; NoError AD=1
ietf.org. IN DNSKEY 256 3 5 AwEAAdDECajHaTjfSoNTY58WcBah1BxPKVIHBz4IfLjfqMvium4lgKtKZLe97DgJ5/NQrNEGGQmr6fKvUj67cfrZUojZ2cGRizVhgkOqZ9scaTVXNuXLM5Tw7VWOVIceeXAuuH2mPIiEV6MhJYUsW6dvmNsJ4XwCgNgroAmXhoMEiWEjBB+wjYZQ5GtZHBFKVXACSWTiCtddHcueOeSVPi5WH94VlubhHfiytNPZLrObhUCHT6k0tNE6phLoHnXWU+6vpsYpz6GhMw/R9BFxW5PdPFIWBgoWk2/XFVRSKG9Lr61b2z1R126xeUwvw46RVy3hanV3vNO7LM5HniqaYclBbhk= ; NoError AD=1
ietf.org. IN DNSKEY 257 3 5 AwEAAavjQ1H6pE8FV8LGP0wQBFVL0EM9BRfqxz9p/sZ+8AByqyFHLdZcHoOGF7CgB5OKYMvGOgysuYQloPlwbq7Ws5WywbutbXyG24lMWy4jijlJUsaFrS5EvUu4ydmuRc/TGnEXnN1XQkO+waIT4cLtrmcWjoY8Oqud6lDaJdj1cKr2nX1NrmMRowIu3DIVtGbQJmzpukpDVZaYMMAm8M5vz4U2vRCVETLgDoQ7rhsiD127J8gVExjO8B0113jCajbFRcMtUtFTjH4z7jXP2ZzDcXsgpe4LYFuenFQAcRBRlE6oaykHR7rlPqqmw58nIELJUFoMcb/BdRLgbyTeurFlnxs= ; NoError AD=1
ietf.org. IN MX 0 mail.ietf.org. ; NoError AD=1
mail.ietf.org. IN A 4.31.198.44 ; NoError AD=1
mail.ietf.org. IN AAAA 2001:1900:3001:11::2c ; NoError AD=1
_25._tcp.mail.ietf.org. IN TLSA 3 1 1 0c72ac70b745ac19998811b131d662c9ac69dbdbe7cb23e5b514b56664c5d3d6 ; NoError AD=1
  mail.ietf.org[4.31.198.44]: pass: TLSA match: depth = 0, name = ietf.org
    TLS = TLS12 with ECDHE-RSA-AES256GCM-SHA384
    name = *.ietf.org
    name = ietf.org
    depth = 0
      Issuer CN = Starfield Secure Certificate Authority - G2
      notBefore = 2017-06-12T10:12:00Z
      notAfter = 2018-08-11T23:12:50Z
      Subject CN = *.ietf.org
      pkey sha256 [matches] <- 3 1 1 0c72ac70b745ac19998811b131d662c9ac69dbdbe7cb23e5b514b56664c5d3d6
    depth = 1
      Issuer CN = Starfield Root Certificate Authority - G2
      notBefore = 2011-05-03T07:00:00Z
      notAfter = 2031-05-03T07:00:00Z
      Subject CN = Starfield Secure Certificate Authority - G2
      pkey sha256 [nomatch] <- 2 1 1 f24196ae94078667348f02e8e37458a3a6e6aad1e0b0dc610118cce721427bfc
    depth = 2
      Issuer CN = -
      notBefore = 2014-01-01T07:00:00Z
      notAfter = 2031-05-30T07:00:00Z
      Subject CN = Starfield Root Certificate Authority - G2
      pkey sha256 [nomatch] <- 2 1 1 808d68b3fab4884a5f971ace7d10550d7a95a163774f3ec36afffb213fbe4c74
    depth = 3
      Issuer CN = -
      notBefore = 2004-06-29T17:39:16Z
      notAfter = 2034-06-29T17:39:16Z
      Subject CN = -
      pkey sha256 [nomatch] <- 2 1 1 15f14ac45c9c7da233d3479164e8137fe35ee0f38ae858183f08410ea82ac4b4
```

Seems to work fine, so I'm not running into any issues so far.

(I only display certificate CNs for brevity, but in this case the depth 2 issuer/depth 3 self-signed root has no CN, its DN is `/C=US/O=Starfield Technologies, Inc./OU=Starfield Class 2 Certification Authority`)

**Comment by kazu-yamamoto** [comment]
> Thanks, one quick observation... I notice you did not merge the change that changed the 1 ms timeout to 0ms to test a forced timeout. Unfortunately, on my system with a local resolver, a 1 ms timeout does not reliably fail to perform the lookup, while 0ms does work. Please consider adopting that change

Understood and done.
