### ISSUE TITLE
Irrefutable pattern failed for pattern l : _

### ISSUE THREAD

**Issue by cleverca22** [kazu-yamamoto/dns#71]
https://github.com/kazu-yamamoto/dns/blob/125fa9a49a2f68e4d1e625e11cdce373c6a8df8b/Network/DNS/Resolver.hs#L144
`Network/DNS/Resolver.hs:144:21-71: Irrefutable pattern failed for pattern l : _`

```
[root@instance1:~]# cat /etc/resolv.conf 
# Generated by resolvconf
options edns0
options edns0
```

it appears that a lack of any `nameserver` entry causes this rather unreadable error, it should at least throw a readable error message, or handle the lack of a nameserver better

**Comment by kazu-yamamoto** [comment]
This should be fixed in c5a1cc79e7e92f2a51358d1bcab2a827b07bf95e
