### ISSUE TITLE
BadOpt

### ISSUE THREAD

**Issue by kazu-yamamoto** [kazu-yamamoto/dns#75]
@greydot You introduced `BadOpt` which is assigned to 6.
But https://www.iana.org/assignments/dns-parameters/dns-parameters.xhtml#dns-parameters-6 assigns `YXDomain` for 6.

I would like to fix this mismatch for code readability. Note that I don't understand how `BadOpt` is generated yet.

Relating to #30.

**Comment by greydot** [comment]
>But https://www.iana.org/assignments/dns-parameters/dns-parameters.xhtml#dns-parameters-6 assigns YXDomain for 6.
Probably a typo on my part. It is supposed to be 16.

>Note that I don't understand how BadOpt is generated yet.
It is supposed to be emited when OPT record version is not supported. I suppose, this will be the case some day when or if EDNS1 is released.

**Comment by kazu-yamamoto** [comment]
OK.

- 16 is an extended rcode.
- We cannot use enum for 0..5 and 16.

It is a little bit complicated to fix all these above in the `master` branch.
So, I have fixed these with pattern synonyms in the `ghc8` branch (e24f98db95548393791e962d57988e3e10286abf).
