### ISSUE TITLE
Support IPv6 addresses in Resolver construction

### ISSUE THREAD

**Issue by adinapoli-iohk** [kazu-yamamoto/dns#80]
Hey @kazu-yamamoto !

A colleague of mine stumbled upon an interesting edge-case of this library. Consider the following `/etc/resolv.conf`:

```
#
# Mac OS X Notice
#
# This file is not used by the host name and address resolution
# or the DNS query routing mechanisms used by most processes on
# this Mac OS X system.
#
# This file is automatically generated.
#
domain Speedport_W_724V_Typ_A_05011603_05_020
nameserver fe80::1
nameserver 192.168.2.1
```

See that? The first nameserver is an IPv6 address! Unfortunately, the current revision of the library on `master`, as we speak, cannot handle this file properly, as the testsuite would fail with:

```
### Failure in ./Network/DNS/Lookup.hs:37: expression `withResolver rs $ \resolver -> lookupA resolver hostname'
expected: Right [93.184.216.34]
 but got: *** Exception: Network.Socket.sendBuf: does not exist (No route to host)
### Failure in ./Network/DNS/Lookup.hs:88: expression `withResolver rs $ \resolver -> lookupA resolver hostname'
expected: Right [210.130.207.72]
 but got: *** Exception: Network.Socket.sendBuf: does not exist (No route to host)
### Failure in ./Network/DNS/Lookup.hs:120: expression `withResolver rs $ \resolver -> lookupAAAA resolver hostname'
expected: Right [2001:200:dff:fff1:216:3eff:fe4b:651c]
 but got: *** Exception: Network.Socket.sendBuf: does not exist (No route to host)
### Failure in ./Network/DNS/Lookup.hs:149: expression `withResolver rs $ \resolver -> lookupMX resolver hostname'
expected: Right []
 but got: *** Exception: Network.Socket.sendBuf: does not exist (No route to host)
### Failure in ./Network/DNS/Lookup.hs:185: expression `ips <- withResolver rs $ \resolver -> lookupAviaMX resolver hostname'
expected: 
 but got: *** Exception: Network.Socket.sendBuf: does not exist (No route to host)
### Failure in ./Network/DNS/Lookup.hs:261: expression `ns <- withResolver rs $ \resolver -> lookupNS resolver hostname'
expected: 
 but got: *** Exception: Network.Socket.sendBuf: does not exist (No route to host)
### Failure in ./Network/DNS/Lookup.hs:308: expression `withResolver rs $ \resolver -> lookupTXT resolver hostname'
expected: Right ["v=spf1 +mx -all"]
 but got: *** Exception: Network.Socket.sendBuf: does not exist (No route to host)
### Failure in ./Network/DNS/Lookup.hs:335: expression `withResolver rs $ \resolver -> lookupPTR resolver hostname'
expected: Right ["www.iij.ad.jp."]
 but got: *** Exception: Network.Socket.sendBuf: does not exist (No route to host)
### Failure in ./Network/DNS/Lookup.hs:362: expression `withResolver rs $ \resolver -> lookupRDNS resolver hostname'
expected: Right ["www.iij.ad.jp."]
 but got: *** Exception: Network.Socket.sendBuf: does not exist (No route to host)
### Failure in ./Network/DNS/Lookup.hs:400: expression `withResolver rs $ \resolver -> lookupSRV resolver q'
expected: Right [(5,0,5269,"jabber.ietf.org.")]
 but got: *** Exception: Network.Socket.sendBuf: does not exist (No route to host)
### Failure in ./Network/DNS/Resolver.hs:272: expression `withResolver rs $ \resolver -> lookup resolver hostname A'
expected: Right [RD_A 93.184.216.34]
 but got: *** Exception: Network.Socket.sendBuf: does not exist (No route to host)
Examples: 93  Tried: 78  Errors: 0  Failures: 11

Lookup
  lookup
    lookupA FAILED [1]
    lookupAAAA FAILED [2]
    lookupAAAA with emty result FAILED [3]
    lookupMX FAILED [4]
    lookupTXT FAILED [5]
    lookupNS FAILED [6]

Failures:

  test2/LookupSpec.hs:28: 
  1) Lookup.lookup lookupA
       uncaught exception: IOException of type NoSuchThing (Network.Socket.sendBuf: does not exist (No route to host))

  test2/LookupSpec.hs:35: 
  2) Lookup.lookup lookupAAAA
       uncaught exception: IOException of type NoSuchThing (Network.Socket.sendBuf: does not exist (No route to host))

  test2/LookupSpec.hs:42: 
  3) Lookup.lookup lookupAAAA with emty result
       uncaught exception: IOException of type NoSuchThing (Network.Socket.sendBuf: does not exist (No route to host))

  test2/LookupSpec.hs:49: 
  4) Lookup.lookup lookupMX
       uncaught exception: IOException of type NoSuchThing (Network.Socket.sendBuf: does not exist (No route to host))

  test2/LookupSpec.hs:56: 
  5) Lookup.lookup lookupTXT
       uncaught exception: IOException of type NoSuchThing (Network.Socket.sendBuf: does not exist (No route to host))

  test2/LookupSpec.hs:63: 
  6) Lookup.lookup lookupNS
       uncaught exception: IOException of type NoSuchThing (Network.Socket.sendBuf: does not exist (No route to host))

Randomized with seed 603664375

Finished in 0.0222 seconds
6 examples, 6 failures

Decode
  decode
    decodes double pointers correctly
    decodes dname
    decodes txt
    decodes mx
Encode
  encode
    encodes DNSMessage correctly
  decode
    decodes DNSMessage correctly
RoundTrip
  IPv4
  IPv6
  TYPE
  Domain
  DNSFlags
  ResourceRecord
  DNSHeader
  DNSMessage

Finished in 0.1721 seconds
14 examples, 0 failures
```

Without digging too much into the code, I can see two problems inside [makeResolvSeed](https://github.com/kazu-yamamoto/dns/blob/master/Network/DNS/Resolver.hs#L151-L178):

1. It stops eagerly at the first `nameserver` throwing away the secondary one which might be useful to use later on in case the primary fails.

2. The `extract` function seems a bit hairy (but I might be wrong). Cannot we simply use the `read` instance of the [ip-route](http://hackage.haskell.org/package/iproute) package you wrote to simply deal correctly with both type of addresses?

If you think I'm on the right track, would you accept a PR for this? (unless you beat me to that, of course 😉 )

Thank you very much!

**Comment by kazu-yamamoto** [comment]
OK. My understanding is:

- `dns` lib can handle IPv6 address in `resolv.conf` properly
- But your host is not IPv6-enabled

And yes, it is a good idea to try the next DNS server in this case.

**Comment by adinapoli-iohk** [comment]
After looking a bit better to the code I do agree with you, @kazu-yamamoto !

Would you be OK with me sending a PR later this week where I:

* Change the type of `ResolvSeed` to have at least a primary DNS and a optional secondary one, like this:

``` haskell
data ResolvSeed = ResolvSeed {
    primaryDNS :: AddrInfo
  , secondaryDNS :: AddrInfo
  , rsTimeout :: Int
  , rsRetry :: Int
  , rsBufsize :: Integer
}
```

Then, extend [lookupRawInternal](https://github.com/kazu-yamamoto/dns/blob/master/Network/DNS/Resolver.hs#L386) to try the secondary DNS once we exhausted the retries, resetting the retry counter. Once we exhausted all the alternatives, we finally declare defeat by throwing `RetryLimitExceeded` like before.

Sounds reasonable enough?

**Comment by adinapoli-iohk** [comment]
Uhm, now that I see the code, I think it _might_ make sense to keep the 1:1 ResolvSeed:Resolver ratio and simply have `makeResolvSeed` to return a `[ResolvSeed]`, one for each `nameserver` found in `/etc/resolv.conf`. I will explore the solution space a little bit.

**Comment by kazu-yamamoto** [comment]
I guess it would be better to add a new function rather than to change the signature of the current function.

**Comment by adinapoli-iohk** [comment]
> I guess it would be better to add a new function rather than to change the signature of the current function.

@kazu-yamamoto I have been exploring different solutions and this is what I have currently got so far (WIP):

https://github.com/kazu-yamamoto/dns/compare/master...input-output-hk:issue-80

I like the current design because it doesn't brake user code but at the same time allows `lookupRawInternal` to be extended. Do you think I'm on the right track? (the current WIP has been tested and all the doctests passes)

**Comment by kazu-yamamoto** [comment]
I'm on a trip. So, very quick review.
I think you are on the right track.

**Comment by adinapoli-iohk** [comment]
> I'm on a trip. So, very quick review.

I hope a leisure one! 😉 

> I think you are on the right track.

Happy to hear that! there is a PR ready for you which includes all this goodness, when you are back from the trip I will be curious to hear what you think 😉

**Comment by kazu-yamamoto** [comment]
@adinapoli-iohk Please close this issue if possible.

**Comment by adinapoli-iohk** [comment]
Maybe I can nudge Mr @kantp to try this out for me? 😜

**Comment by adinapoli-iohk** [comment]
Confirmed with my colleague that this is now working as intended 😉
