### ISSUE TITLE
Replace System.Random

### ISSUE THREAD

**Issue by kazu-yamamoto** [kazu-yamamoto/dns#90]
We need

- fast
- thread-safe

alternative.

**Comment by vdukhovni** [comment]
In addition to fast and thread safe, also cryptographically strong.  On Unix systems, just reading 2 bytes from /dev/urandom is likely fast enough, secure and thread safe for unbuffered reads.  Of course we could also FFI into the C API and use getentropy() on systems that have that.

Otherwise, instead of sharing an RNG across multiple Resolver objects, we could instantiate a new RNG for each one.  In which case AES in counter mode works well enough, but we still need to seed that.  Getting a securely seeded low-cost secure RNG is a bit non-trivial...

**Comment by kazu-yamamoto** [comment]
Good point!
Do you have any idea to get seeds on Windows?

**Comment by kazu-yamamoto** [comment]
Let's just use `cryptonite`.
It uses `/dev/urandom` on Unix and CryptoAPI on Windows.
Very good.

**Comment by vdukhovni** [comment]
To be honest, while cryptonite is probably fine, perhaps https://hackage.haskell.org/package/DRBG-0.5.5/docs/Crypto-Random-DRBG.html is better suited for our simpler needs. The author claims good performance, and the package does not try to be a complete crypto toolkit.  Take a look and see what you think.

**Comment by kazu-yamamoto** [comment]
It depends on the `entropy` package which uses `/dev/urandom` on Unix and CryptoAPI on Windows.
So, both `cryptonite` and `DRBG` are fine to me.

**Comment by vdukhovni** [comment]
May I leave the choice to you?  If you have time, take a look "under the hood" and see which package you prefer (performance, API, code quality, dependencies, code size...).

Lot's of users are perhaps already using cryptonite indirectly for TLS, so adding that as a dependency is perhaps not too burdensome, but DRBG looks like a smaller footprint choice that's just a crypto RNG and nothing else. I don't know what to make of today's discussion on Haskell Cafe of changing it to avoid periodic reseeding...

**Comment by kazu-yamamoto** [comment]
For the record, Thomas kindly introduced this blog:
http://tommd.github.io/posts/RNG-Bench.html

**Comment by kazu-yamamoto** [comment]
Deterministic Random Bit Generators: NIST SP 800-90

https://web.archive.org/web/20070926201210/http://csrc.nist.gov/publications/nistpubs/800-90/SP800-90revised_March2007.pdf

**Comment by kazu-yamamoto** [comment]
ChaCha in cryptonite: https://tools.ietf.org/html/rfc7539

**Comment by kazu-yamamoto** [comment]
I guess that ChaCha (2015) is more modern than NIST SP 800-90 (2007).

**Comment by kazu-yamamoto** [comment]
@vdukhovni I would like to vote for `cryptonite`
- Specification is more modern (2015 vs 2007)
- I prefer RFC to NIST spec
- Development of `cryptonito` is active

Could you have time to develop the random stuff based on `cryptonite`?

**Comment by kazu-yamamoto** [comment]
@vdukhovni Please review the commit above.

**Comment by kazu-yamamoto** [comment]
This has been merged.
Please reopen if necessary.
