### ISSUE TITLE
Feature Request: lookupSOA

### ISSUE THREAD

**Issue by polynomial** [kazu-yamamoto/dns#92]
It would be awesome if this library supported looking up SOA[1] records for a domain. This would be useful for:

* people wanting to validate their zone configuration
* lookup abuse addresses to contact for a domain from inside a Haskell program

I am new to Haskell, so I hope I am not missing a way to do this in the current lookup utilities!

1: https://en.wikipedia.org/wiki/SOA_Resource_Record

**Comment by kazu-yamamoto** [comment]
`Network.DNS.Resolver.lookup` can look up any records: https://hackage.haskell.org/package/dns-2.0.13/docs/Network-DNS-Resolver.html#g:5

Just specify 'SOA'.

**Comment by kazu-yamamoto** [comment]
Oh, do you mean that you want to add `lookupSOA`?

**Comment by polynomial** [comment]
Yeah, sorry for the confusion! I was going to try and add it, maybe it will not be the worst. (:

**Comment by polynomial** [comment]
I have submitted PR #93 to address this! Please let me know if there is anything I can do to improve it.

**Comment by kazu-yamamoto** [comment]
PR #93 has been merged. So, let's close this.
